spring:
  # Basic Config
  application:
    name: gibbu

  # JPA Config
  jpa:
    show-sql: false
    database: postgresql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

# Logging config
logging:
  level:
    root: INFO
