spring:
  config:
    # Profile config
    activate:
      on-profile: local
    # .env file config
    import:
      - optional:file:.env[.properties]

  # Local DB config
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: ${LOCAL_DB_DRIVER_CLASS_NAME}

  # Local JPA config
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Logging config
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG