spring:
  config:
    import:
      - application-secret.yml
    activate:
      on-profile: prod

  # Prod DB config
  datasource:
    url: ${DATABASE.PROD.url}
    username: ${DATABASE.PROD.username}
    password: ${DATABASE.PROD.password}
    driver-class-name: ${DATABASE.PROD.driver-class-name}

  # Prod JPA config
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Logging config
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG