spring:
  config:
    import:
      - application-secret.yml
    activate:
      on-profile: dev

  # Dev DB config
  datasource:
    url: ${DATABASE.DEV.url}
    username: ${DATABASE.DEV.username}
    password: ${DATABASE.DEV.password}
    driver-class-name: ${DATABASE.DEV.driver-class-name}

  # Dev JPA config
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Logging config
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

server:
  port: 8081