name: Gibbu CD

on:
  workflow_run:
    workflows: [ "Gibbu CI" ]
    types: [ "completed" ]
    branches: [ "dev", "main" ]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Set deployment environment
        run: |
          if [ "${{ github.event.workflow_run.head_branch }}" == "dev" ]; then
            echo "SERVER_HOST=${{ secrets.DEV_SERVER_HOST }}" >> $GITHUB_ENV
            echo "SPRING_PROFILE=dev" >> $GITHUB_ENV
          elif [ "${{ github.event.workflow_run.head_branch }}" == "main" ]; then
            echo "SERVER_HOST=${{ secrets.PROD_SERVER_HOST }}" >> $GITHUB_ENV
            echo "SPRING_PROFILE=prod" >> $GITHUB_ENV
          fi

      - name: Execute deployment script on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            WORKDIR="/home/${{ secrets.EC2_USER }}/gibbu"
            mkdir -p $WORKDIR
            cd $WORKDIR

            echo "${{ secrets.ENV_VARS }}" > ./.env

            export DOCKER_IMAGE_TAG=${{ github.event.workflow_run.head_sha }}
            echo "${{ vars.DOCKER_COMPOSE }}" > ./docker-compose.yaml

            docker-compose pull
            docker-compose down
            docker-compose up -d

            docker image prune -af